services:
  - type: web
    name: osint-scout
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT osint_scout_flask:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
